# Setup
title:               Cadenze
tagline:             'aka Boris Li'
description:         'Look to the past, and see further for the future.'
url:                 http://www.cadenze.ca
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Boris Li
  github:            Cadenze
  instagram:         caden.ze
  twitter:           caden_ze
  linkedin:          cadenze
  discord:           https://discord.gg/eTtJwKJ
  youtube:           UCj4YnKsa5NaphpexMTfu2OQ
  goodreads:         
  orcid:             
  google_scholar:    
  email:             borisowenli@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
# google_analytics_id: #UA-XXXX-Y