# Dependencies
# markdown:         kramdown
# highlighter:      rouge # changed from `pygments` as github says so

# Permalinks
permalink:        pretty

# Setup
title:            'Cadenze'
tagline:          'aka Boris Li'
description:      'Look to the past, and see further for the future.'
url:              http://www.cadenze.ca
baseurl:          ''
paginate:         5
paginate_path:    '/blog/page:num/'

author:
  name: 'Boris Li'
  email: 'borisowenli[at]gmail[dot]com'
  github: Cadenze





  # google_analytics_id: UA-27104497-1
  # google_analytics_url: 
  bio: UBC Science Student
