# Dependencies
# markdown:         redcarpet
# highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            One Weekly
# tagline:          'A Jekyll theme'
description:      'Weekly updates on assignments, reading, and notes as well as links to all textbooks used in Science One'
url:              'https://onesci.github.io'
baseurl:          ''


# author:
#  name:           
#  url:            

 paginate:         5

# Custom vars
# version:          2.1.0

# github:
#  repo:           
